spring.datasource.url=jdbc:mysql://localhost:3306/bookstoremanager
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=developer
spring.datasource.password=a220197

spring.jpa.show-sql=false
spring.jpa.properties.hibernate=
spring.jpa.properties.format_sql=true

spring.h2.console.enabled=true

logging.level.br.com.masantello=TRACE