# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=DEV01
spring.datasource.password=DEV0123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate=
spring.jpa.properties.format_sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=true

logging.level.br.com.masantello=TRACE